export const FETCH_DATA_ACTION = 'FETCH_DATA_ACTION';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const RESET_DATA = 'RESET_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';